name: winged_staccato
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+3
  google_fonts: ^1.1.1
  harmony_sdk: ^0.0.6
  protobuf: ^1.1.0
  tuple: ^1.0.3
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  flutter_inner_drawer: ^0.5.7+2

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  hive_generator: ^0.8.2
  build_runner: ^1.10.11
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
